Feature: MakingAmnesiaAgent

  Scenario: MakingAmnesiaAgent
    Given that everything is reset
    Given object "Virologist"
    Then I should be told "Virologist objektum sikeresen létrehozva."
    Given object "AmnesiaGeneticCode"
    Then I should be told "AmnesiaGeneticCode objektum sikeresen létrehozva."
    Given I added to "Virologist1" virologist "AmnesiaGeneticCode" genetic code
    Then I should be told "Genetikai kód sikeresen hozzáadva."
    Given object "AminoAcidMaterial"
    Then I should be told "AminoAcidMaterial objektum sikeresen létrehozva."
    Given object "AminoAcidMaterial"
    Then I should be told "AminoAcidMaterial objektum sikeresen létrehozva."
    Given object "AminoAcidMaterial"
    Then I should be told "AminoAcidMaterial objektum sikeresen létrehozva."
    Given object "AminoAcidMaterial"
    Then I should be told "AminoAcidMaterial objektum sikeresen létrehozva."
    Given object "AminoAcidMaterial"
    Then I should be told "AminoAcidMaterial objektum sikeresen létrehozva."
    Given object "NucleotideMaterial"
    Then I should be told "NucleotideMaterial objektum sikeresen létrehozva."
    Given object "NucleotideMaterial"
    Then I should be told "NucleotideMaterial objektum sikeresen létrehozva."
    Given object "NucleotideMaterial"
    Then I should be told "NucleotideMaterial objektum sikeresen létrehozva."
    Given object "NucleotideMaterial"
    Then I should be told "NucleotideMaterial objektum sikeresen létrehozva."
    Given object "NucleotideMaterial"
    Then I should be told "NucleotideMaterial objektum sikeresen létrehozva."
    Given I added "AminoAcidMaterial1 AminoAcidMaterial2 AminoAcidMaterial3 AminoAcidMaterial4 AminoAcidMaterial5 NucleotideMaterial1 NucleotideMaterial2 NucleotideMaterial3 NucleotideMaterial4 NucleotideMaterial5" materials to "Virologist1"
    Then I should be told "Anyagok sikeresen hozzáadva."
    Given Virologist "Virologist1" makes inactive agent "AmnesiaGeneticCode1"
    Then I should be told "Inaktív ágens készítése sikeres."