Feature: PickupMaterialWhileFull

    Scenario: PickupMaterialWhileFull
        Given that everything is reset
        Given object "Virologist"
        Then I should be told "Virologist objektum sikeresen létrehozva."
        Given object "StorageTile"
        Then I should be told "StorageTile objektum sikeresen létrehozva."
        Given object "NucleotideMaterial"
        Then I should be told "NucleotideMaterial objektum sikeresen létrehozva."
        Given object "NucleotideMaterial"
        Then I should be told "NucleotideMaterial objektum sikeresen létrehozva."
        Given object "NucleotideMaterial"
        Then I should be told "NucleotideMaterial objektum sikeresen létrehozva."
        Given object "NucleotideMaterial"
        Then I should be told "NucleotideMaterial objektum sikeresen létrehozva."
        Given object "NucleotideMaterial"
        Then I should be told "NucleotideMaterial objektum sikeresen létrehozva."
        Given object "NucleotideMaterial"
        Then I should be told "NucleotideMaterial objektum sikeresen létrehozva."
        Given object "NucleotideMaterial"
        Then I should be told "NucleotideMaterial objektum sikeresen létrehozva."
        Given object "NucleotideMaterial"
        Then I should be told "NucleotideMaterial objektum sikeresen létrehozva."
        Given object "NucleotideMaterial"
        Then I should be told "NucleotideMaterial objektum sikeresen létrehozva."
        Given object "NucleotideMaterial"
        Then I should be told "NucleotideMaterial objektum sikeresen létrehozva."
        Given object "NucleotideMaterial"
        Then I should be told "NucleotideMaterial objektum sikeresen létrehozva."
        Given Virologist "Virologist1" moves to Tile "StorageTile1"
        Then I should be told "Mozgás StorageTile1 mezőre sikeres."
        Given I added to StorageTile "StorageTile1" "NucleotideMaterial1 NucleotideMaterial2 NucleotideMaterial3 NucleotideMaterial4 NucleotideMaterial5" materials
        Then I should be told "Anyagok sikeresen hozzáadva."
        Given Virologist "Virologist1" picks up materials "NucleotideMaterial1 NucleotideMaterial2 NucleotideMaterial3 NucleotideMaterial4 NucleotideMaterial5"
        Then I should be told "Anyagok felvétele sikeres."
        Given I added to StorageTile "StorageTile1" "NucleotideMaterial6 NucleotideMaterial7 NucleotideMaterial8 NucleotideMaterial9 NucleotideMaterial10" materials
        Then I should be told "Anyagok sikeresen hozzáadva."
        Given Virologist "Virologist1" picks up materials "NucleotideMaterial6 NucleotideMaterial7 NucleotideMaterial8 NucleotideMaterial9 NucleotideMaterial10"
        Then I should be told "Anyagok felvétele sikeres."
        Given I added to StorageTile "StorageTile1" "NucleotideMaterial11" materials
        Then I should be told "Anyagok sikeresen hozzáadva."
        Given Virologist "Virologist1" picks up materials "NucleotideMaterial11"
        Then I should be told "Anyagok felvétele sikertelen."
